name: Cypress Tests

on:
  push:
    branches:
      - master
      - cypress-screenshots

  workflow_dispatch:

jobs:
  run-cypress-tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: pnpm setup
        uses: pnpm/action-setup@v4
        with:
          version: 8
          run_install: false

      - name: Install dependancies
        run: pnpm install --no-frozen-lockfile

      - name: Run build
        run: npm run build

      - name: Run Application
        run: npm run dev & 
  
      - name: Run Cypress
        run: pnpm cypress run
      
      - name: Upload screenshots
        uses: actions/upload-artifact@v3
        if: failure()
        with:
          name: cypress-screenshots
          path: cypress/screenshots
